name = "tic-tac-toe-v2"
main = "src/index.ts"
compatibility_date = "2026-02-25"

[[durable_objects.bindings]]
name = "GAME"
class_name = "Game"
script_name = "tic-tac-toe-v2"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Game"]

[observability]
enabled = true
